import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import {
  classicStorageKey,
  commitLegacySessionImport,
  convertClassicSession,
  hasClassicMigrationProvenance,
  inspectLegacySession,
  isLegacyScoreSaveBlocked,
} from "../mobile_app/legacy_session_migration.mjs";
import { computeResultSummary, scoreForCorrect } from "../mobile_app/quiz_core.mjs";

// Generated by the real Python build_classic_session_snapshot, rather than a
// second JavaScript implementation of the legacy serialization contract.
const fixtures = JSON.parse(readFileSync(new URL("./fixtures/classic_session_migration.json", import.meta.url), "utf8"));
const mobileKey = "esperanto-choice-mobile:session:v2";
const context = { targetLang: "ja", mode: "vocab", source: "vocab_app_ja", appVersion: "test" };
const snapshot = () => structuredClone(fixtures.vocabFeedback);

function memoryStorage(initial = {}) {
  const items = new Map(Object.entries(initial));
  return {
    getItem: (key) => items.has(key) ? items.get(key) : null,
    setItem: (key, value) => items.set(key, String(value)),
    removeItem: (key) => items.delete(key),
  };
}

function completedSnapshot({ saved = false, pendingSaveId = null } = {}) {
  const value = snapshot();
  Object.assign(value.state, {
    q_index: 2,
    showing_result: false,
    spartan_mode: false,
    spartan_pending: [],
    score_saved: saved,
    pending_save_id: pendingSaveId,
  });
  return value;
}

test("vocabulary import keeps the answer screen, points, settings, and original snapshot", async () => {
  const old = snapshot();
  const before = structuredClone(old);
  const { status, session } = await convertClassicSession(old, context);
  assert.equal(status, "ready");
  assert.equal(session.status, "active");
  assert.equal(session.source, context.source);
  assert.equal(session.settings.userName, "Learner");
  assert.equal(session.settings.seed, 7);
  assert.equal(session.settings.groupId, "noun:beginner_1:g1");
  assert.equal(session.qIndex, 1);
  assert.equal(session.correct, 1);
  assert.equal(session.showingFeedback, true);
  assert.deepEqual(session.feedback, { correct: false, selectedIndex: 3, message: "不正解。正解: 火" });
  assert.equal(session.mainPoints, 10);
  assert.deepEqual(session.spartanPending, [1]);
  assert.deepEqual(session.answers.map((answer) => [answer.qIndex, answer.selectedIndex, answer.phase]), [[0, 0, "main"], [1, 3, "main"]]);
  assert.equal(session.questions[1].promptEo, "fajro");
  assert.equal(session.questions[1].promptJa, "火");
  assert.equal(session.questions[0].options[0].audioKey, "akvo");
  assert.equal(scoreForCorrect(session.questions[0], 1), 10);
  assert.deepEqual(old, before);
});

test("sentence import preserves raw/scaled review points and infers omitted legacy phases", async () => {
  const old = structuredClone(fixtures.sentenceReview);
  const { session, status } = await convertClassicSession(old, {
    targetLang: "ko", mode: "sentence", source: "sentence_app_ko",
    sentenceEntries: [{ id: 156, eo: "Mi lernas.", audioKey: "0001_mi_lernas", hasAudio: true }],
  });
  assert.equal(status, "ready");
  assert.equal(session.inSpartan, true);
  assert.equal(session.spartanCurrent, 0);
  assert.equal(session.spartanAttempts, 2);
  assert.equal(session.spartanCorrect, 1);
  assert.equal(session.spartanRawPoints, old.state.points_spartan_raw);
  assert.equal(session.spartanScaledPoints, old.state.points_spartan_scaled);
  assert.deepEqual(session.answers.map((answer) => answer.phase), ["main", "main", "spartan", "spartan"]);
  assert.equal(session.questions[0].options[0].audioKey, "0001_mi_lernas");
  assert.equal(session.questions[0].options[1].hasAudio, false);
  assert.equal(session.settings.direction, "ja_to_eo");
  assert.equal(scoreForCorrect(session.questions[0], 1), old.state.points_spartan_raw);
});

test("saved complete results never receive a fresh score submission", async () => {
  const { session } = await convertClassicSession(completedSnapshot({ saved: true }), context);
  assert.equal(session.status, "complete");
  assert.equal(session.scoreSyncStatus, "saved");
  assert.equal(session.savedToHistory, false);
  assert.equal(computeResultSummary(session).points, 15);
});

test("an unacknowledged save reuses the exact old idempotency ID", async () => {
  const { session } = await convertClassicSession(completedSnapshot({ pendingSaveId: "retry-with-same-save-id" }), context);
  assert.equal(session.scoreSaveId, "retry-with-same-save-id");
  assert.equal(session.scoreSyncStatus, "idle");
});

test("a repeated conversion always creates the same fallback save ID", async () => {
  const old = completedSnapshot();
  const first = await convertClassicSession(old, context);
  const again = await convertClassicSession(old, { ...context, appVersion: "later" });
  assert.equal(first.session.id, again.session.id);
  assert.equal(first.session.scoreSaveId, again.session.scoreSaveId);
  old.savedAt = "2026-09-06T12:01:00Z";
  assert.notEqual((await convertClassicSession(old, context)).session.id, first.session.id);
});

test("an old complete snapshot with unknown save state is viewable with cloud saving blocked", async () => {
  const old = completedSnapshot();
  delete old.state.score_saved;
  const { status, session } = await convertClassicSession(old, context);
  assert.equal(status, "ready");
  assert.equal(session.status, "complete");
  assert.equal(session.scoreSyncStatus, "error");
  assert.equal(session.scoreSyncRecoverable, "legacy_save_unknown");
  assert.equal(isLegacyScoreSaveBlocked(session), true);
  assert.equal(computeResultSummary(session).points, 15);
});

test("two and three choice classic quizzes keep their original choices and explicit provenance", async () => {
  for (const count of [2, 3]) {
    const old = snapshot();
    old.state.questions[0].options.length = count;
    const { status, session } = await convertClassicSession(old, context);
    assert.equal(status, "ready");
    assert.equal(session.questions[0].options.length, count);
    assert.equal(hasClassicMigrationProvenance(session), true);
    assert.equal(isLegacyScoreSaveBlocked(session), false);
    session.legacyMigration.storageKey = classicStorageKey("zh", "vocab");
    assert.equal(hasClassicMigrationProvenance(session), false);
  }
});

test("corrupt question indexes, point values, and answer histories are rejected", async () => {
  for (const mutate of [
    (old) => { old.state.answers[0].q_idx = "__proto__"; },
    (old) => { old.state.main_points = Infinity; },
    (old) => { old.state.correct = 2; },
    (old) => { old.state.questions[0].answer_index = 8; },
    (old) => { old.state.answers[1].selected = 10; },
    (old) => { old.state.spartan_pending = [1, 1]; },
    (old) => { old.state.pending_save_id = 123; },
  ]) {
    const old = snapshot();
    mutate(old);
    assert.equal((await convertClassicSession(old, context)).status, "invalid");
  }
});

test("only the selected language and mode can be migrated", async () => {
  const selected = classicStorageKey("ja", "vocab");
  const alternate = classicStorageKey("ko", "sentence");
  const storage = memoryStorage({ [alternate]: JSON.stringify(fixtures.sentenceReview) });
  assert.equal((await inspectLegacySession({ storage, ...context })).status, "none");
  storage.setItem(selected, JSON.stringify(snapshot()));
  const candidate = await inspectLegacySession({ storage, ...context });
  assert.equal(candidate.status, "ready");
  assert.equal(candidate.storageKey, selected);
  assert.equal((await convertClassicSession(fixtures.sentenceReview, context)).status, "invalid");
});

test("an existing mobile quiz, including unreadable raw storage, is never overwritten", async () => {
  for (const current of [JSON.stringify({ status: "active" }), "broken-json", "null", ""]) {
    const storage = memoryStorage({ [mobileKey]: current });
    assert.equal((await inspectLegacySession({ storage, ...context })).status, "current-session");
    assert.equal(storage.getItem(mobileKey), current);
  }
  assert.equal((await inspectLegacySession({ storage: memoryStorage(), currentSession: {}, ...context })).status, "current-session");
});

test("import persists once and preserves every original classic key", async () => {
  const legacyKey = classicStorageKey("ja", "vocab");
  const raw = JSON.stringify(snapshot());
  const storage = memoryStorage({ [legacyKey]: raw, unrelated: "keep" });
  const candidate = await inspectLegacySession({ storage, ...context });
  assert.deepEqual(commitLegacySessionImport({ storage, candidate }), { ok: true, markerSaved: true });
  assert.equal(JSON.parse(storage.getItem(mobileKey)).id, candidate.session.id);
  assert.equal(storage.getItem(legacyKey), raw);
  assert.equal(storage.getItem("unrelated"), "keep");
  storage.removeItem(mobileKey);
  assert.equal((await inspectLegacySession({ storage, ...context })).status, "handled");
  const rewritten = snapshot();
  rewritten.savedAt = "2026-09-06T12:01:00Z";
  storage.setItem(legacyKey, JSON.stringify(rewritten));
  assert.equal((await inspectLegacySession({ storage, ...context })).status, "handled");
});

test("another tab starting a new mobile quiz while the prompt is open blocks import", async () => {
  const storage = memoryStorage({ [classicStorageKey("ja", "vocab")]: JSON.stringify(snapshot()) });
  const candidate = await inspectLegacySession({ storage, ...context });
  storage.setItem(mobileKey, "new-session");
  assert.deepEqual(commitLegacySessionImport({ storage, candidate }), { ok: false, reason: "current-session" });
  assert.equal(storage.getItem(mobileKey), "new-session");
});

test("advancing the old quiz while the prompt is open requires fresh inspection", async () => {
  const legacyKey = classicStorageKey("ja", "vocab");
  const storage = memoryStorage({ [legacyKey]: JSON.stringify(snapshot()) });
  const candidate = await inspectLegacySession({ storage, ...context });
  storage.setItem(legacyKey, JSON.stringify(completedSnapshot()));
  assert.deepEqual(commitLegacySessionImport({ storage, candidate }), { ok: false, reason: "legacy-session-changed" });
  assert.equal(storage.getItem(mobileKey), null);
});

test("storage access denial and corrupt JSON produce actionable outcomes without deletion", async () => {
  const blocked = { getItem() { throw new Error("SecurityError"); } };
  assert.deepEqual(await inspectLegacySession({ storage: blocked, ...context }), { status: "storage-unavailable", reason: "SecurityError" });
  const key = classicStorageKey("ja", "vocab");
  const storage = memoryStorage({ [key]: "{invalid" });
  const candidate = await inspectLegacySession({ storage, ...context });
  assert.equal(candidate.reason, "invalid-json");
  assert.equal(candidate.raw, "{invalid");
  assert.equal(storage.getItem(key), "{invalid");
});

test("quota failure leaves the original quiz intact and makes no import marker", async () => {
  const key = classicStorageKey("ja", "vocab");
  const raw = JSON.stringify(snapshot());
  const storage = memoryStorage({ [key]: raw });
  const candidate = await inspectLegacySession({ storage, ...context });
  storage.setItem = () => { throw new Error("QuotaExceededError"); };
  const outcome = commitLegacySessionImport({ storage, candidate });
  assert.equal(outcome.ok, false);
  assert.equal(outcome.reason, "storage-unavailable");
  assert.equal(storage.getItem(key), raw);
  assert.equal(storage.getItem(mobileKey), null);
});

test("marker failure retains the durable imported quiz and stable save ID", async () => {
  const storage = memoryStorage({ [classicStorageKey("ja", "vocab")]: JSON.stringify(snapshot()) });
  const candidate = await inspectLegacySession({ storage, ...context });
  const originalWrite = storage.setItem;
  storage.setItem = (key, value) => {
    if (key !== mobileKey) throw new Error("QuotaExceededError");
    originalWrite(key, value);
  };
  const outcome = commitLegacySessionImport({ storage, candidate });
  assert.equal(outcome.ok, true);
  assert.equal(outcome.markerSaved, false);
  assert.equal(JSON.parse(storage.getItem(mobileKey)).scoreSaveId, candidate.session.scoreSaveId);
});
